//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingSpace()
        {
            this.ParkingUnits = new HashSet<ParkingUnit>();
        }
    
        public string ParkingSpace_Name { get; set; }
        public bool Status { get; set; }
        public int Max_Capacity { get; set; }
        public int Current_Capacity { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingUnit> ParkingUnits { get; set; }
    }
}
