//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingUnit()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Unit_Number { get; set; }
        public bool Avalilability { get; set; }
        public string ParkingSpace_Name { get; set; }
    
        public virtual ParkingSpace ParkingSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
