//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_Number { get; set; }
        public string Vehicle_Reg { get; set; }
        public int cost { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public string Ticket_Duration { get; set; }
        public int Unit_Number { get; set; }
        public string User { get; set; }
    
        public virtual ParkingUnit ParkingUnit { get; set; }
    }
}
